# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Java CI with Maven
on:
  schedule:
    # UTC
    - cron: '30 0 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run Java Application
        run: java -jar target/daily-wallpaper-1.0.0.jar

      - name: Commit files
        env:
          ACTION_WORK_KEY: ${{ secrets.DAILY }}
          COMMIT_EMAIL: ${{ secrets.EMAIL }}
        run: |
          mkdir -p ~/.ssh
          echo "$ACTION_WORK_KEY" > ~/.ssh/id_rsa
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --local user.email "$COMMIT_EMAIL"
          git config --local user.name "arminzheng"
          git add -A
          git commit -m "update daily paper"
          git push origin main
